version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=mydatabase
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - lotf-network

networks:
  lotf-network:
    external: true
